In [3]:
import numpy as np
mystr = "hello\nworld"
str1, str2 = mystr.split('\n')
print(f"str1 = {str1}, str2 = {str2}")

str1 = hello, str2 = world


In [4]:
array = np.arange(36).reshape(6,6)
print(array)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [ ]:
while True:
    T = input("Please input a temperature: ")
    try:
        T = float(T)
        break
    except ValueError:
        print("Please input a number.")